# CREATE TABLE YourTable (
#     ID INT PRIMARY KEY,
#     Column1 VARCHAR(255),
#     Column2 VARCHAR(255),
#     ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START,
#     ValidTo DATETIME2 GENERATED ALWAYS AS ROW END,
#     PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
# ) WITH (SYSTEM_VERSIONING = ON);

# DELETE FROM YourTable WHERE CAST(ValidFrom AS DATE) < CAST(GETDATE() AS DATE);